pai_parcel_homepage:
    path:     /
    defaults: { _controller: PAIParcelBundle:Default:index }

pai_parcel_Parcel:
    type: rest
    prefix: /v1
    resource: 'PAI\ParcelBundle\Controller\ParcelController'
    name_prefix: api_1_ #naming collision